---

user_name: arch
user_group: arch
user_shell: /bin/bash
user_uid: 1000
user_gid: 1000
user_pass_hash: '$6$vultr.arch$a41beHtZ6/9A0eHjfII3VyArafuiGSFxXYas.LOR6dehb44EW6V0d.HxwHB5oiMTwXj.I3oE3cB/D8F1QvZFt1'

system:
  timezone: America/Toronto
  locale: en_US.UTF-8

docker_app_data: /docker

ssh_setting:
  port: 22
  password_authentication: "no"
  root_login: "no"
  challenge_response_authentication: "no"

# mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64373533373961643363653535316263396135356361386366326433656537663031316161323766
          6461326364613138396633306662623439616434343261390a663664396166343233366364376531
          34393333313332326331636430353839616130613931323962626464636434356462396338643765
          3361663533646562610a383863666238643866633765353865343162666534626266626539326234
          3161
mysql_user: ${mysql_user}
mysql_database: ${mysql_database}
# mysql_password: "{{ vault_mysql_password }}"
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64373533373961643363653535316263396135356361386366326433656537663031316161323766
          6461326364613138396633306662623439616434343261390a663664396166343233366364376531
          34393333313332326331636430353839616130613931323962626464636434356462396338643765
          3361663533646562610a383863666238643866633765353865343162666534626266626539326234
          3161

samba_shares_root: /mnt/

media_downloads: "{{ samba_shares_root }}/downloads"
media_movies: "{{ samba_shares_root }}/movies"
media_tv: "{{ samba_shares_root }}/tv/tv"
media_torrents: "{{ samba_shares_root }}/torrents"

heimdall_container_name: heimdall
heimdall_container_store: linuxserver
heimdall_config_directory: "{{ docker_app_data }}/heimdall"
heimdall_version: latest
heimdall_port_http: 9050
heimdall_port_https: 9052

dillinger_container_name: dillinger
dillinger_container_store: linuxserver
dillinger_version: latest
dillinger_port: 9902

nextcloud_container_name: nextcloud
nextcloud_container_store: linuxserver
nextcloud_version: latest
nextcloud_port: 9983

mariadb_container_name: mariadb
mariadb_container_store: linuxserver
mariadb_config_directory: "{{ docker_app_data }}/mariadb"
mariadb_version: latest
mariadb_port: 3306
mariadb_root_password: "{{ mysql_root_password }}"

bookstack_container_name: bookstack
bookstack_container_store: linuxserver
bookstack_config_directory: "{{ docker_app_data }}/bookstack"
bookstack_version: latest
bookstack_port_http: 6875
bookstack_db_container: bookstack_db
bookstack_db_config_directory: "{{ docker_app_data }}/bookstack/mysql"
bookstack_db_root_password: "{{ mysql_root_password }}"
bookstack_db_name: bookstackapp
bookstack_db_user: bookstack
bookstack_db_host: bookstack_db
bookstack_root_password: "{{ mysql_root_password }}"

portainer_container_name: portainer
portainer_container_store: portainer
portainer_config_directory: "{{ docker_app_data }}/portainer"
portainer_version: latest
portainer_port: 9000

plex_container_name: plex
plex_container_store: linuxserver
plex_config_directory: "{{ docker_app_data }}/plex"
plex_version: latest

base:
  packages:
    - git
    - curl
    - aria2
    - bash-completion
    - htop
    - unzip
    - zip
    - tree
    - tmux
    - man-db
    - coreutils
    - python3
    - python3-pip

server:
  packages:
  fonts:

workstation:
  packages:
  fonts:
