---

- name: Create Grafana Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "472"
    recurse: yes
  with_items:
    - "{{ grafana_config_directory }}"
    - "{{ grafana_config_directory }}/data"
    - "{{ grafana_config_directory }}/data/dashboards/rhinocerose"
    - "{{ grafana_config_directory }}/config/"
    - "{{ grafana_config_directory }}/config/provisioning"
    - "{{ grafana_config_directory }}/config/provisioning/datasources"
    - "{{ grafana_config_directory }}/config/provisioning/dashboards"

- name: grafana Docker Container
  docker_container:
    name: "{{ grafana_container_name }}"
    image: "{{ grafana_container_store }}/{{ grafana_container_name }}:{{ grafana_version }}"
    pull: true
    volumes:
      - "{{ grafana_config_directory }}/data:/var/lib/grafana:rw"
      - "{{ grafana_config_directory }}/config/provisioning:/etc/grafana/provisioning:ro"
    ports:
      - "{{ grafana_port }}:3000"
    env:
      TZ: "{{ system.timezone }}"
      PUID: "{{ user_uid | string }}"
      PGID: "{{ user_gid | string }}"
    restart_policy: unless-stopped
