---

- name: Create heimdall directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  with_items:
    - "{{ heimdall_config_directory }}"

- name: heimdall Docker Container
  docker_container:
    name: "{{ heimdall_container_name }}"
    image: "{{ heimdall_container_store }}/{{ heimdall_container_name }}:{{ heimdall_version }}"
    pull: true
    volumes:
      - "{{ heimdall_config_directory }}:/config"
      - "{{ docker_app_data }}/shared:/shared"
    ports:
      - "{{ heimdall_port_http }}:80/tcp"
      - "{{ heimdall_port_https }}:443/tcp"
    env:
      TZ: "{{ system.timezone }}"
      PUID: "{{ user_uid | string }}"
      PGID: "{{ user_gid | string }}"
    restart_policy: unless-stopped
