---

- name: Create couchpotato directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  with_items:
    - "{{ couchpotato_config_directory }}"

- name: couchpotato Docker Container
  docker_container:
    name: "{{ couchpotato_container_name }}"
    image: "{{ couchpotato_container_store }}/{{ couchpotato_container_name }}:{{ couchpotato_version }}"
    pull: true
    volumes:
      - "{{ couchpotato_config_directory }}:/config"
      - "{{ media_downloads }}:/downloads:rw"
      - "{{ media_torrents }}:/torrents:rw"
      - "{{ media_movies }}:/data/movies:rw"
    ports:
      - "{{ couchpotato_port }}:5050"
    env:
      TZ: "{{ system.timezone }}"
      PUID: "{{ user_uid | string }}"
      PGID: "{{ user_gid | string }}"
    restart_policy: unless-stopped
