---

- name: Create jellyfin directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  with_items:
    - "{{ jellyfin_config_directory }}"

- name: jellyfin Docker Container
  docker_container:
    name: "{{ jellyfin_container_name }}"
    image: "{{ jellyfin_container_store }}/{{ jellyfin_container_name }}:{{ jellyfin_version }}"
    pull: true
    volumes:
      - "{{ jellyfin_config_directory }}/config:/config"
      # - "{{ docker_app_data }}/{{ jellyfin_container_name }}/transcode:/transcode"
      - "{{ media_tv }}:/data/tv"
      - "{{ media_movies }}:/data/movies"
    ports:
      - "{{ jellyfin_port_http }}:8096"
    env:
      TZ: "{{ system.timezone }}"
      PUID: "{{ user_uid | string }}"
      PGID: "{{ user_gid | string }}"
    restart_policy: unless-stopped
