---

- name: Create plex directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: 0755
  with_items:
    - "{{ docker_app_data }}/{{ plex_container_name }}"

- name: plex Docker Container
  docker_container:
    name: "{{ plex_container_name }}"
    image: "{{ plex_container_store }}/{{ plex_container_name }}:{{ plex_version }}"
    pull: true
    volumes:
      - "{{ docker_app_data }}/{{ plex_container_name }}/library:/config"
      - "{{ docker_app_data }}/{{ plex_container_name }}/transcode:/transcode"
      - "{{ media_tv }}:/data/tv"
      - "{{ media_movies }}:/data/movies"
    ports:
      - "{{ plex_port }}:32400"
      - "{{ plex_port }}:32400/udp"
      - "32469:32469"
      - "32469:32469/udp"
      - "5353:5353/udp"
      - "1900:1900/udp"
    env:
      TZ: "{{ system.timezone }}"
      PUID: "{{ user_uid | string }}"
      PGID: "{{ user_gid | string }}"
    restart_policy: unless-stopped
