---

- name: Ensure Nginx Docker Container is absent
  docker_container:
    name: nginx-proxy
    state: absent

- name: Nginx Letsencrypt Container is absent
  docker_container:
    name: letsencrypt-nginx-proxy-companion
    state: absent

- name: Create Traefik Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_config_directory }}"

- name: Template Traefik config.toml
  template:
    src: "traefik.toml"
    dest: "{{ traefik_config_directory }}/traefik.toml"

- name: Traefik Docker Container
  docker_container:
    name: "{{ traefik_container_name }}"
    image: "{{ traefik_container_name }}/{{ traefik_version }}"
    pull: true
    network_mode: host
    volumes:
      - "{{ traefik_config_directory }}/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart_policy: unless-stopped
